import {createSlice} from '@reduxjs/toolkit';
import syltherine from "@/assets/furniture/syltherine.png";
import liviosa from "@/assets/furniture/leviosa.png";
import lolito from "@/assets/furniture/lolito.png";
import respira from "@/assets/furniture/respira.png";
import grifo from "@/assets/furniture/grifo.png";
import muggo from "@/assets/furniture/muggo.png";
import pingky from "@/assets/furniture/pingky.png";
import potty from "@/assets/furniture/potty.png";

export type ProductType = {
    id: number
    src: string
    alt: string
    title: string
    description: string
    price: string
    oldPrice: string
    status: string
    quantity: number
}

const initialState: ProductType[] = [
    {
        id: 1,
        src: syltherine,
        alt: 'syltherine',
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        price: '2500000',
        oldPrice: '3.500.000',
        status: '-30%',
        quantity: 1,
    },
    {
        id: 2,
        src: liviosa,
        alt: 'liviosa',
        title: 'Liviosa',
        description: 'Stylish cafe chair',
        price: '2500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 3,
        src: lolito,
        alt: 'lolito',
        title: 'Lolito',
        description: 'Luxury big sofa',
        price: '7000000',
        oldPrice: '14.000.000',
        status: '-50%',
        quantity: 1,
    },
    {
        id: 4,
        src: respira,
        alt: 'respira',
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        price: '500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 5,
        src: grifo,
        alt: 'grifo',
        title: 'Grifo',
        description: 'Night lamp',
        price: '1500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 6,
        src: muggo,
        alt: 'muggo',
        title: 'Muggo',
        description: 'Small mug',
        price: '150000',
        oldPrice: '',
        status: 'New',
        quantity: 1,
    },
    {
        id: 7,
        src: pingky,
        alt: 'pingky',
        title: 'Pingky',
        description: 'Cute bed set',
        price: '7000000',
        oldPrice: '14.000.000',
        status: '-50%',
        quantity: 1,
    },
    {
        id: 8,
        src: potty,
        alt: 'potty',
        title: 'Potty',
        description: 'Minimalist flower pot',
        price: '1500000',
        oldPrice: '',
        status: 'New',
        quantity: 1,
    },
    {
        id: 9,
        src: syltherine,
        alt: 'syltherine',
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        price: '2500000',
        oldPrice: '3.500.000',
        status: '-30%',
        quantity: 1,
    },
    {
        id: 10,
        src: liviosa,
        alt: 'liviosa',
        title: 'Liviosa',
        description: 'Stylish cafe chair',
        price: '2500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 11,
        src: lolito,
        alt: 'lolito',
        title: 'Lolito',
        description: 'Luxury big sofa',
        price: '7000000',
        oldPrice: '14.000.000',
        status: '-50%',
        quantity: 1,
    },
    {
        id: 12,
        src: respira,
        alt: 'respira',
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        price: '500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 13,
        src: grifo,
        alt: 'grifo',
        title: 'Grifo',
        description: 'Night lamp',
        price: '1500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 14,
        src: muggo,
        alt: 'muggo',
        title: 'Muggo',
        description: 'Small mug',
        price: '150000',
        oldPrice: '',
        status: 'New',
        quantity: 1,
    },
    {
        id: 15,
        src: pingky,
        alt: 'pingky',
        title: 'Pingky',
        description: 'Cute bed set',
        price: '7000000',
        oldPrice: '14.000.000',
        status: '-50%',
        quantity: 1,
    },
    {
        id: 16,
        src: potty,
        alt: 'potty',
        title: 'Potty',
        description: 'Minimalist flower pot',
        price: '1500000',
        oldPrice: '',
        status: 'New',
        quantity: 1,
    },
    {
        id: 17,
        src: syltherine,
        alt: 'syltherine',
        title: 'Syltherine',
        description: 'Stylish cafe chair',
        price: '2500000',
        oldPrice: '3.500.000',
        status: '-30%',
        quantity: 1,
    },
    {
        id: 18,
        src: liviosa,
        alt: 'liviosa',
        title: 'Liviosa',
        description: 'Stylish cafe chair',
        price: '2500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 19,
        src: lolito,
        alt: 'lolito',
        title: 'Lolito',
        description: 'Luxury big sofa',
        price: '7000000',
        oldPrice: '14.000.000',
        status: '-50%',
        quantity: 1,
    },
    {
        id: 20,
        src: respira,
        alt: 'respira',
        title: 'Respira',
        description: 'Outdoor bar table and stool',
        price: '500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 21,
        src: grifo,
        alt: 'grifo',
        title: 'Grifo',
        description: 'Night lamp',
        price: '1500000',
        oldPrice: '',
        status: '',
        quantity: 1,
    },
    {
        id: 22,
        src: muggo,
        alt: 'muggo',
        title: 'Muggo',
        description: 'Small mug',
        price: '150000',
        oldPrice: '',
        status: 'New',
        quantity: 1,
    },
    {
        id: 23,
        src: pingky,
        alt: 'pingky',
        title: 'Pingky',
        description: 'Cute bed set',
        price: '7000000',
        oldPrice: '14.000.000',
        status: '-50%',
        quantity: 1,
    },
    {
        id: 24,
        src: potty,
        alt: 'potty',
        title: 'Potty',
        description: 'Minimalist flower pot',
        price: '1500000',
        oldPrice: '',
        status: 'New',
        quantity: 1,
    },
]

export type AppInitialStateType = ReturnType<typeof productSlice.getInitialState>

export const productSlice = createSlice({
        name: 'products',
        initialState,
        reducers:{}
    }
)

//export const {getCurrentProduct} = productSlice.actions;
export const productReducer = productSlice.reducer